
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const TermsOfService = () => {
  return (
    <div className="bg-near_black min-h-screen">
      <Header />
      
      <div className="pt-24 pb-16">
        <div className="container-custom max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>
          <p className="text-sm text-light_gray_text/70 mb-8">Last Updated: October 15, 2023</p>
          
          <div className="prose prose-lg prose-invert max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using XEUR.AI's website, platform, or services ("Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use our Services.
            </p>
            
            <h2>2. Description of Services</h2>
            <p>
              XEUR.AI provides an AI-powered platform for creating games and interactive experiences from text prompts. Our Services may include features such as game generation, editing, exporting, and publishing capabilities.
            </p>
            
            <h2>3. User Accounts</h2>
            <p>
              To access certain features of our Services, you must create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
            </p>
            <p>
              You agree to provide accurate and complete information when creating your account and to update your information to keep it accurate and current. We reserve the right to suspend or terminate accounts that provide inaccurate, fraudulent, or outdated information.
            </p>
            
            <h2>4. Subscription and Payments</h2>
            <p>
              Some aspects of our Services require payment of fees. By subscribing to a paid plan, you agree to pay all fees in accordance with the billing terms in effect at the time of your subscription.
            </p>
            <p>
              Unless otherwise specified:
            </p>
            <ul>
              <li>All fees are quoted in United States Dollars (USD)</li>
              <li>Payments are non-refundable</li>
              <li>We reserve the right to change our prices with reasonable notice</li>
            </ul>
            
            <h2>5. Intellectual Property Rights</h2>
            <h3>5.1 Our Intellectual Property</h3>
            <p>
              The Services, including all content, features, and functionality, are owned by XEUR.AI or its licensors and are protected by copyright, trademark, and other intellectual property laws. You may not modify, reproduce, distribute, create derivative works of, publicly display, or publicly perform any of our proprietary materials except as explicitly permitted by these Terms.
            </p>
            
            <h3>5.2 Your Content</h3>
            <p>
              Subject to your compliance with these Terms and any applicable subscription limitations:
            </p>
            <ul>
              <li>You retain all rights to the text prompts you provide to our Services</li>
              <li>You own all rights to the games and assets generated by our Services based on your prompts</li>
              <li>You may use, modify, distribute, and monetize games created using our Services in accordance with your subscription plan</li>
            </ul>
            
            <h3>5.3 License Grant to XEUR.AI</h3>
            <p>
              You grant us a non-exclusive, worldwide, royalty-free license to use, store, and process your content for the purpose of providing and improving our Services. This includes the right to use anonymized data derived from your usage for improving our AI models.
            </p>
            
            <h2>6. Acceptable Use</h2>
            <p>
              When using our Services, you agree not to:
            </p>
            <ul>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Create games that contain illegal, offensive, or harmful content</li>
              <li>Use the Services to distribute malware or other harmful code</li>
              <li>Attempt to gain unauthorized access to our systems or other users' accounts</li>
              <li>Use the Services to generate content that promotes discrimination, harassment, or violence</li>
              <li>Reverse engineer or attempt to extract the source code of our software</li>
            </ul>
            
            <h2>7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, XEUR.AI and its officers, directors, employees, and agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses resulting from:
            </p>
            <ul>
              <li>Your use or inability to use our Services</li>
              <li>Any unauthorized access to or use of our servers and/or personal information</li>
              <li>Any interruption or cessation of transmission to or from our Services</li>
              <li>Any bugs, viruses, or other harmful code that may be transmitted through our Services</li>
            </ul>
            
            <h2>8. Disclaimer of Warranties</h2>
            <p>
              The Services are provided "as is" and "as available" without warranties of any kind, either express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, or non-infringement.
            </p>
            
            <h2>9. Indemnification</h2>
            <p>
              You agree to defend, indemnify, and hold harmless XEUR.AI and its officers, directors, employees, and agents from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses arising from your use of the Services or your violation of these Terms.
            </p>
            
            <h2>10. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to our Services at any time for any reason, including but not limited to, violation of these Terms. Upon termination, your right to use the Services will immediately cease.
            </p>
            
            <h2>11. Changes to These Terms</h2>
            <p>
              We may revise these Terms from time to time. The most current version will always be posted on our website. If a revision, in our sole discretion, is material, we will notify you via email or through the Services. By continuing to use our Services after revisions become effective, you agree to be bound by the revised Terms.
            </p>
            
            <h2>12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions.
            </p>
            
            <h2>13. Contact</h2>
            <p>
              If you have any questions or concerns about these Terms, please contact us at legal@xeur.ai.
            </p>
          </div>
        </div>
      </div>
      
      <Footer />
    </div>
  );
};

export default TermsOfService;
